---
- name: Learning to Use Ansible for Windows automation
  hosts: windows
  #connection: winrm   # we already mapped this in our inventory
  gather_facts: true

  tasks:
  
    - name: What did gather_facts return?
      ansible.builtin.debug:
        msg: 
          - "{{ ansible_facts.interfaces }}"
          - "{{ ansible_facts.processor }}"
          - "{{ ansible_facts.memtotal_mb }}"
