---
- name: Testing Windows Connection
  hosts: windows
  connection: winrm

  tasks:

  - name: A windows version of the classic ping module
    #ansible.windows.win_ping:
    win_ping:
       data: "I'm he for whom tho seekests"           # Alternate data to return instead of 'pong'

