---
- name: create a new users
  hosts: windows
  connection: winrm
  gather_facts: true
  
  vars_files:
    - new_users.yaml
  
  tasks:
    - name: Add New Users
      ansible.windows.win_user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        state: present
      loop: "{{ new_users }}"
