---
- name: Exploring the template module and jinja expressions
  hosts: windows
  connection: winrm
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used in the template ship.cfg.j2
  vars:
    ship_name: Bessie
    ship_type: Intergalactic
    engines: Dark Matter
    dark_matter_balls: 63
    backup_engines: Chemical


  tasks:
    - name: configure spaceship registration
      ansible.windows.win_template:  
        src: templates/ship.cfg.j2    # name of the template on ansible controller
        dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\ship.cfg"              # name of the completed file to be placed on the target system

