- name: Ensure state var is set to present
  set_fact:
    state: "present"

- name: Create a resource group
  azure.azcollection.azure_rm_resourcegroup:
    state: "{{ state }}"
    name: "{{ rg_name }}"
    location: "{{ rg_location }}"
    tags: "(( tags }}"

- name: Create virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ rg_name }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_cidr }}"

- name: Add subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ rg_name }}"
    name: "{{ sn_name }}"
    address_prefix: "{{ sn_cidr }}"
    virtual_network: "{{ vnet_name }}"

- name: Create public ip
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ rg_name }}"
    allocation_method: "{{ pubip_method }}"
    name: "{{ pubip_name }}"

- name: Create security group that allows SSH
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ rg_name }}"
    name: "{{ sg_name }}"
    rules:
      - name: "{{ sg_rule_name }}"
        protocol: "{{ sg_rule_proto }}"
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: "{{ sg_rule_dir }}"

- name: Create NIC
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ rg_name }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ sn_name }}"
    public_ip_name: "{{ pubip_name }}"
    security_group: "{{ sg_name }}"



- name: Create virtual machine
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: "{{ vm_name }}"
    state: "{{ state }}"
    vm_size: "{{ vm_size }}"   # for a list see --> https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2
    managed_disk_type: "{{ vm_disk }}"
    admin_username: "{{ vm_user }}"
    admin_password: "{{ vm_pw }}"
    network_interfaces: "{{ nic_name }}" # for list of images see --> https://az-vm-image.info/
    image: "{{ vm_image }}"

